svr:oj_server.cpp
	g++ $^ -o $@ -g -lpthread -I /home/test/Linux/project/online_OJ/lib_file/ThirdPartLibForCpp/el7.x86_64/third_part/include -L /home/test/Linux/project/online_OJ/lib_file/ThirdPartLibForCpp/el7.x86_64/third_part/lib -lctemplate
