svr:oj_server.cpp
	g++ $^ -o $@ -g -lpthread -I /home/test/Linux/project/library_file/ThirdPartLibForCpp/el7.x86_64/third_part/include -I /usr/include/jsoncpp -L /home/test/Linux/project/library_file/ThirdPartLibForCpp/el7.x86_64/third_part/lib -lctemplate -ljsoncpp
