all:producter broadcast procom sem
producter:producter.c
	g++ $^ -o $@ -lpthread
broadcast:broadcast.c
	g++ $^ -o $@ -lpthread
procom:procom.cpp
	g++ $^ -o $@ -lpthread
sem:sem.cpp
	g++ $^ -o $@ -lpthread
